name: CI/CD-DEV
on:
  push:
    branches: dev0*

jobs:
  builddev:
    runs-on: ubuntu-latest
    environment: development
    steps:    
    - name: "Checkout GitHub Action"
      uses: actions/checkout@v2
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: hirata11/devops-template
        path: template
    - name: templateBuild
      uses: ./template/build/front/frontdev
      with:
        env: $(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})

  deploydev:
    runs-on: ubuntu-latest
    needs: builddev
    environment: development
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          path: template    
      - name: templateDeploy
        uses: ./template/deploy/front/frontdev
        with:
          token: ${{ secrets.TOKEN }}
          env: $(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})

  buildhml:
    runs-on: ubuntu-latest
    needs: deploydev
    environment: homologation
    steps:    
    - name: "Checkout GitHub Action"
      uses: actions/checkout@v2
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: hirata11/devops-template
        path: template
    - name: templateBuild
      uses: ./template/build/front/fronthml
      with:
        env: $(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})

  deployhml:
    runs-on: ubuntu-latest
    needs: buildhml
    environment: homologation
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: hirata11/devops-template
          path: template    
      - name: templateDeploy
        uses: ./template/deploy/front/fronthml
        with:
          token: ${{ secrets.TOKEN }}
          env: $(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})
