name: FrontEnd
on: 
  workflow_dispatch:
  release:
    types: published
env:
  APP: reactstatic # nome da aplicação.
  IMAGE: frontend #nome da imagem

jobs:
  builddev:
    runs-on: ubuntu-latest
    steps:    
    - id: latest
      uses: thebritican/fetch-latest-release@v2.0.0
      with:
        github_token: ${{ secrets.PAT }}    

    - name: "Checkout GitHub Action"
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.latest.outputs.tag_name }}      

    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: hirata11/devops-template
        token: ${{ secrets.PAT }} 
        path: template

    - name: templateBranch
      uses: ./template/build/branch
      with:
        tag: ${{ steps.latest.outputs.tag_name }}
        token: ${{ secrets.PAT }}

    - name: templateBuild
      uses: ./template/build/front

  deploydev:
    runs-on: ubuntu-latest
    needs: builddev
    environment: development
    steps:
      - id: latest
        uses: thebritican/fetch-latest-release@v2.0.0
        with:
          github_token: ${{ secrets.PAT }}

    - name: templateDeploy
      uses: ./template/deploy/front
      with:
        tag: ${{ steps.latest.outputs.tag_name }}
        token: ${{ secrets.TOKEN }}
        pat: ${{ secrets.PAT }}

  rollbackprd:
      runs-on: ubuntu-latest
      needs: deploydev
      environment: rollback
      steps:
        - run: npm i -g @azure/static-web-apps-cli
        - id: latestdel
          uses: thebritican/fetch-latest-release@v2.0.0
          with:
            github_token: ${{ secrets.PAT }} 
        - name: getreleaseid  
          run: |
            release=$(curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }} " \
              https://api.github.com/repos/hirata11/${{ env.APP }}/releases/tags/${{ steps.latestdel.outputs.tag_name }}  | jq '.id')
            echo $release
            curl \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }} " \
              https://api.github.com/repos/hirata11/${{ env.APP }}/releases/$release
          shell: bash
        - run: |
            sleep 1m
            curl -sL https://api.github.com/repos/hirata11/${{ env.APP }}/releases/latest | jq -r ".tag_name"
          shell: bash

        - name: get lastest release
          id: lastestRelease
          run: echo "::set-output name=releasename::$(curl -sL https://api.github.com/repos/hirata11/${{ env.APP }}/releases/latest | jq -r ".tag_name")"

        - name: templateDeploy
          uses: ./template/deploy/front
          with:
            tag: ${{ steps.lastestRelease.outputs.releasename }}
            token: ${{ secrets.TOKEN }}
            pat: ${{ secrets.PAT }}
  
  ProductionOK:
      runs-on: ubuntu-latest
      needs: deploydev
      environment: production
      steps:
        - id: latest
          uses: thebritican/fetch-latest-release@v2.0.0
          with:
            github_token: ${{ secrets.PAT }}        
        - name:
          uses: tukasz/direct-merge-action@master
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            source-branch: 'release-${{ steps.latest.outputs.tag_name }}'
            target-branch: master
            commit-message: "Liberada a versão ${{ steps.latest.outputs.tag_name }}" 
      