name: CI/CD-HML
on:
  workflow_dispatch:
  push:
    branches: dev01
    
  mergedev:
    runs-on: ubuntu-latest
    needs: deployhml
    steps:
      - name: Create Pull Request
        id: prdev02
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update changelog
          title: "An automatically created PR!"
          body: Update branch to reflect new version changes
          branch: dev02
          base: dev01
          
      - name: Create Pull Request
        id: prdev01
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update changelog
          title: "An automatically created PR!"
          body: Update branch to reflect release changes
          branch: dev01
          base: dev02
