name: CI/CD-HML
on:
  workflow_dispatch:
  push:
    branches: dev01
jobs:   
  mergedev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        id: prdev02
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update changelog
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "An automatically created PR!"
          body: Update branch to reflect new version changes
          labels: |
            cicd
            automated pr
          branch: dev02
          base: dev01
          
      - name: Create Pull Request
        id: prdev01
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update changelog
          title: "An automatically created PR!"
          body: Update branch to reflect release changes
          branch: dev01
          base: dev02
